image: docker:latest

build:
  only:
    - tags
  cache:
    untracked: true
    paths:
      - node_modules/
  script:
    - docker ps >> /dev/null
    - apk add --update git nodejs bash
    - git config --global url.https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.com/.insteadOf git://gitlab.com/
    - git config --global url.https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.com/cgps.insteadOf git@gitlab.com:cgps
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - ./bin/build-image.sh $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
