image: docker:latest
services:
 - docker:dind
 - node:6.9.1
new-image:
  only:
    - tags
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - sh ./bin/build-image.sh $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
