image: docker:latest

build:
  only:
    - tags
  cache:
    untracked: true
    paths:
      - node_modules/
  script:
    - docker ps >> /dev/null
    - apk add --update git nodejs
    - git config --global url.https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.com/.insteadOf git://gitlab.com/
    - git config --global url.https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.com/cgps.insteadOf git@gitlab.com:cgps
    - npm install --production --ignore-scripts
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - tag=$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker build --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy -t $tag .
    - docker push $tag
