image: node:10.12.0-alpine

build:
  only:
    - tags
  # cache:
  #   untracked: true
  #   paths:
  #     - node_modules/
  script:
    - apk add --update docker
    - docker login
      --username gitlab-ci-token
      --password $CI_JOB_TOKEN $CI_REGISTRY
    - tag=$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker build
      --force-rm
      --tag $tag
      --build-arg REPO_USER=gitlab-ci-token 
      --build-arg REPO_TOKEN=${CI_JOB_TOKEN}
      --build-arg http_proxy=$http_proxy
      --build-arg https_proxy=$https_proxy
      .
    - docker push
      $tag
    - docker rmi
      --force
      $tag
