module.exports = {
  ANTIMICROBIALS: 'AMAS',
  ASSEMBLY_METADATA: 'AM',
  COLLECTION_LIST: 'CL',
  CORE_RESULT: 'CR',
  CORE_TREE_RESULT: 'CTR',
  FP_COMP: 'FPR',
  MLST_RESULT: 'MLSTR',
  PAARSNP_RESULT: 'PSR',
  UPLOAD_PROGRESS: 'UP'
};
