module.exports = {
  ANTIMICROBIALS: 'AMAS',
  ASSEMBLY_METADATA: 'AM',
  COLLECTION_LIST: 'CL',
  COLLECTION_METADATA: 'CMD',
  CORE_RESULT: 'CR',
  CORE_TREE_RESULT: 'CTR',
  FP_COMP: 'FPR',
  MLST_RESULT: 'MLSTR',
  PAARSNP_RESULT: 'PSR',
  NGMAST_RESULT: 'NGMASTR',
};
