module.exports = {
  ANTIMICROBIALS: 'AMAS',
  ASSEMBLY_METADATA: 'AM',
  COLLECTION_LIST: 'CL',
  CORE_SLIM: 'CS',
  CORE_TREE_RESULT: 'CTR',
  FP_COMP: 'FPR',
  MLST_RESULT: 'MLSTR',
  PAARSNP_RESULT: 'PSR',
};
