# This is a basic workflow to help you get started with Actions

name: Build a versioned image

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      # As from https://stackoverflow.com/questions/63308904/push-to-gitlab-with-access-token-using-github-actions
      - name: Push to GitLab
        env:
          token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
        run: |
          echo Starting push of ${GITHUB_REF_NAME} to GitLab.
          echo test, and deploy your project.
          git config user.name "dr.yeats"
          git config user.email "corin.yeats@cgps.group"
          git remote set-url origin "https://oauth2:${token}@gitlab.com/cgps/pathogenwatch/website.git"
          git push origin --follow-tags ${GITHUB_REF_NAME}
