# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow when tags are pushed
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      # As from https://stackoverflow.com/questions/63308904/push-to-gitlab-with-access-token-using-github-actions
      - name: Push to GitLab
        env:
          token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
        run: |
          echo Starting push of ${GITHUB_REF_NAME} to GitLab.
          echo test, and deploy your project.
          git config user.name "cgps.admin"
          git config user.email "cgps.dev@gmail.com"
          git remote set-url origin "https://oauth2:${token}@gitlab.com/cgps/pathogenwatch/website.git"
          git push origin --follow-tags ${GITHUB_REF_NAME}
